### ISSUE TITLE
Failed to activate the rustsym package

### ISSUE THREAD

**Issue by royvandewater** [miqid/atom-rustsym#5] opened 2017-10-04 15:17 UTC
[Enter steps to reproduce:]

1. With Atom closed, open a project (folder) from the command line (`atom .`) without any Rust files. In my case, both a Golang, and a Node.js project cause this issue.
2. ...

**Atom**: 1.21.0 x64
**Electron**: 1.6.9
**OS**: Mac OS X 10.12.6
**Thrown From**: [rustsym](https://github.com/miqid/atom-rustsym) package 0.4.0

### Stack Trace

Failed to activate the rustsym package

```
At Cannot read property 'name' of undefined

TypeError: Cannot read property 'name' of undefined
    at /packages/rustsym/lib/main.js:74:34
    at Array.find (native)
    at prioritizeCommandListener (/packages/rustsym/lib/main.js:71:28)
    at Package.updateOverrideCommands (/packages/rustsym/lib/main.js:102:3)
    at Package.activate (/packages/rustsym/lib/main.js:23:38)
    at Package.module.exports.Package.activateNow (/Applications/Atom.app/Contents/Resources/app/src/package.js:253:25)
    at /Applications/Atom.app/Contents/Resources/app/src/package.js:225:38
    at Package.module.exports.Package.measure (/Applications/Atom.app/Contents/Resources/app/src/package.js:99:21)
    at /Applications/Atom.app/Contents/Resources/app/src/package.js:218:32
    at Package.module.exports.Package.activate (/Applications/Atom.app/Contents/Resources/app/src/package.js:215:40)
    at PackageManager.activatePackage (/Applications/Atom.app/Contents/Resources/app/src/package-manager.js:690:42)
    at config.transactAsync (/Applications/Atom.app/Contents/Resources/app/src/package-manager.js:665:36)
    at Config.module.exports.Config.transactAsync (/Applications/Atom.app/Contents/Resources/app/src/config.js:367:24)
    at PackageManager.activatePackages (/Applications/Atom.app/Contents/Resources/app/src/package-manager.js:663:23)
    at PackageManager.activate (/Applications/Atom.app/Contents/Resources/app/src/package-manager.js:646:50)
    at /Applications/Atom.app/Contents/Resources/app/src/atom-environment.js:854:36
```

### Commands

```
```

### Non-Core Packages

```
an-old-hope-light-syntax 1.0.1 
an-old-hope-syntax 1.0.4 
atom-alignment 0.13.0 
busy-signal 1.4.3 
go-debug 1.5.2 
go-plus 5.5.5 
go-signature-statusbar 1.2.3 
hyperclick 0.1.5 
intentions 1.1.5 
language-babel 2.75.1 
language-rust 0.4.12 
linter 2.2.0 
linter-eslint 8.3.2 
linter-rust 0.8.0 
linter-shellcheck 1.4.6 
linter-ui-default 1.6.10 
now-syntax 0.2.4 
pubster-syntax 3.0.2 
rustfmt 0.1.3 
rustsym 0.4.0 
seti-ui 1.9.0 
theme-switch 0.5.0 
toggle-quotes 1.0.1 
vim-mode-plus 1.8.1 
```

**Comment by ghost** [comment] 2017-10-08 14:57
Closing this as a duplicate of issue #4.

**Closed as completed by ghost** 2017-10-08 14:57 UTC
